
var MeshUtility = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(moduleArg = {}) {

var l=moduleArg,aa,ba;l.ready=new Promise((a,b)=>{aa=a;ba=b});var ca=Object.assign({},l),da="./this.program",t="";"undefined"!=typeof document&&document.currentScript&&(t=document.currentScript.src);_scriptDir&&(t=_scriptDir);0!==t.indexOf("blob:")?t=t.substr(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1):t="";var ea=l.print||console.log.bind(console),w=l.printErr||console.error.bind(console);Object.assign(l,ca);ca=null;l.thisProgram&&(da=l.thisProgram);var x;l.wasmBinary&&(x=l.wasmBinary);
var noExitRuntime=l.noExitRuntime||!0;"object"!=typeof WebAssembly&&fa("no native wasm support detected");var ha,ia=!1,y,z,ja,ka,A,B,la,ma,D,na=[],oa=[],pa=[];function qa(){var a=l.preRun.shift();na.unshift(a)}var E=0,ra=null,sa=null;function fa(a){if(l.onAbort)l.onAbort(a);a="Aborted("+a+")";w(a);ia=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}function ta(a){return a.startsWith("data:application/octet-stream;base64,")}var F;F="MeshUtility.wasm";
if(!ta(F)){var ua=F;F=l.locateFile?l.locateFile(ua,t):t+ua}function va(a){if(a==F&&x)return new Uint8Array(x);throw"both async and sync fetching of the wasm failed";}function wa(a){return x||"function"!=typeof fetch?Promise.resolve().then(()=>va(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>va(a))}
function xa(a,b,c){return wa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{w(`failed to asynchronously prepare wasm: ${d}`);fa(d)})}function ya(a,b){var c=F;return x||"function"!=typeof WebAssembly.instantiateStreaming||ta(c)||"function"!=typeof fetch?xa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){w(`wasm streaming compile failed: ${e}`);w("falling back to ArrayBuffer instantiation");return xa(c,a,b)}))}
var za=a=>{for(;0<a.length;)a.shift()(l)},Aa=[],Ba=0,H=0;
function Ca(a){this.Za=a;this.Ia=a-24;this.yb=function(b){B[this.Ia+4>>2]=b};this.Ya=function(){return B[this.Ia+4>>2]};this.xb=function(b){B[this.Ia+8>>2]=b};this.sb=function(b){y[this.Ia+12>>0]=b?1:0};this.ub=function(){return 0!=y[this.Ia+12>>0]};this.tb=function(b){y[this.Ia+13>>0]=b?1:0};this.Eb=function(){return 0!=y[this.Ia+13>>0]};this.wb=function(b,c){this.bb(0);this.yb(b);this.xb(c)};this.bb=function(b){B[this.Ia+16>>2]=b};this.ib=function(){return B[this.Ia+16>>2]};this.vb=function(){if(Da(this.Ya()))return B[this.Za>>
2];var b=this.ib();return 0!==b?b:this.Za}}var Ga=a=>{var b=H;if(!b)return Ea(0),0;var c=new Ca(b);c.bb(b);var d=c.Ya();if(!d)return Ea(0),b;for(var e in a){var f=a[e];if(0===f||f===d)break;if(Fa(f,d,c.Ia+16))return Ea(f),b}Ea(d);return b},Ha={},Ia=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Ja(a){return this.fromWireType(A[a>>2])}
var J={},K={},Ka={},La=void 0,M=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new La("Mismatched type converter count");for(var m=0;m<a.length;++m)L(a[m],h[m])}a.forEach(function(h){Ka[h]=b});var e=Array(b.length),f=[],k=0;b.forEach((h,m)=>{K.hasOwnProperty(h)?e[m]=K[h]:(f.push(h),J.hasOwnProperty(h)||(J[h]=[]),J[h].push(()=>{e[m]=K[h];++k;k===f.length&&d(e)}))});0===f.length&&d(e)},Ma=void 0,N=a=>{for(var b="";z[a];)b+=Ma[z[a++]];return b},O=void 0,Na=a=>{throw new O(a);};
function Oa(a,b,c={}){var d=b.name;if(!a)throw new O(`type "${d}" must have a positive integer typeid pointer`);if(K.hasOwnProperty(a)){if(c.Ib)return;throw new O(`Cannot register type '${d}' twice`);}K[a]=b;delete Ka[a];J.hasOwnProperty(a)&&(b=J[a],delete J[a],b.forEach(e=>e()))}function L(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");Oa(a,b,c)}
var Pa=a=>{throw new O(a.Ha.Ka.Ja.name+" instance already deleted");},Qa=!1,Ra=()=>{},Sa=(a,b,c)=>{if(b===c)return a;if(void 0===c.Ma)return null;a=Sa(a,b,c.Ma);return null===a?null:c.Ab(a)},Ta={},Ua=[],Va=()=>{for(;Ua.length;){var a=Ua.pop();a.Ha.Wa=!1;a["delete"]()}},Wa=void 0,Xa={},Ya=(a,b)=>{if(void 0===b)throw new O("ptr should not be undefined");for(;a.Ma;)b=a.ab(b),a=a.Ma;return Xa[b]},$a=(a,b)=>{if(!b.Ka||!b.Ia)throw new La("makeClassHandle requires ptr and ptrType");if(!!b.Oa!==!!b.La)throw new La("Both smartPtrType and smartPtr must be specified");
b.count={value:1};return Za(Object.create(a,{Ha:{value:b}}))},Za=a=>{if("undefined"===typeof FinalizationRegistry)return Za=b=>b,a;Qa=new FinalizationRegistry(b=>{b=b.Ha;--b.count.value;0===b.count.value&&(b.La?b.Oa.Pa(b.La):b.Ka.Ja.Pa(b.Ia))});Za=b=>{var c=b.Ha;c.La&&Qa.register(b,{Ha:c},b);return b};Ra=b=>{Qa.unregister(b)};return Za(a)};function P(){}var ab=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};
function bb(a,b){a=ab(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
var cb=(a,b,c)=>{if(void 0===a[b].Na){var d=a[b];a[b]=function(){if(!a[b].Na.hasOwnProperty(arguments.length))throw new O(`Function '${c}' called with an invalid number of arguments (${arguments.length}) - expects one of (${a[b].Na})!`);return a[b].Na[arguments.length].apply(this,arguments)};a[b].Na=[];a[b].Na[d.cb]=d}},db=(a,b,c)=>{if(l.hasOwnProperty(a)){if(void 0===c||void 0!==l[a].Na&&void 0!==l[a].Na[c])throw new O(`Cannot register public name '${a}' twice`);cb(l,a,a);if(l.hasOwnProperty(c))throw new O(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
l[a].Na[c]=b}else l[a]=b,void 0!==c&&(l[a].Vb=c)};function eb(a,b,c,d,e,f,k,h){this.name=a;this.constructor=b;this.Xa=c;this.Pa=d;this.Ma=e;this.Cb=f;this.ab=k;this.Ab=h;this.Lb=[]}var fb=(a,b,c)=>{for(;b!==c;){if(!b.ab)throw new O(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ab(a);b=b.Ma}return a};
function gb(a,b){if(null===b){if(this.jb)throw new O(`null is not a valid ${this.name}`);return 0}if(!b.Ha)throw new O(`Cannot pass "${hb(b)}" as a ${this.name}`);if(!b.Ha.Ia)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);return fb(b.Ha.Ia,b.Ha.Ka.Ja,this.Ja)}
function ib(a,b){if(null===b){if(this.jb)throw new O(`null is not a valid ${this.name}`);if(this.fb){var c=this.kb();null!==a&&a.push(this.Pa,c);return c}return 0}if(!b.Ha)throw new O(`Cannot pass "${hb(b)}" as a ${this.name}`);if(!b.Ha.Ia)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.eb&&b.Ha.Ka.eb)throw new O(`Cannot convert argument of type ${b.Ha.Oa?b.Ha.Oa.name:b.Ha.Ka.name} to parameter type ${this.name}`);c=fb(b.Ha.Ia,b.Ha.Ka.Ja,this.Ja);if(this.fb){if(void 0===
b.Ha.La)throw new O("Passing raw pointer to smart pointer is illegal");switch(this.Qb){case 0:if(b.Ha.Oa===this)c=b.Ha.La;else throw new O(`Cannot convert argument of type ${b.Ha.Oa?b.Ha.Oa.name:b.Ha.Ka.name} to parameter type ${this.name}`);break;case 1:c=b.Ha.La;break;case 2:if(b.Ha.Oa===this)c=b.Ha.La;else{var d=b.clone();c=this.Mb(c,Q(()=>d["delete"]()));null!==a&&a.push(this.Pa,c)}break;default:throw new O("Unsupporting sharing policy");}}return c}
function jb(a,b){if(null===b){if(this.jb)throw new O(`null is not a valid ${this.name}`);return 0}if(!b.Ha)throw new O(`Cannot pass "${hb(b)}" as a ${this.name}`);if(!b.Ha.Ia)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.Ha.Ka.eb)throw new O(`Cannot convert argument of type ${b.Ha.Ka.name} to parameter type ${this.name}`);return fb(b.Ha.Ia,b.Ha.Ka.Ja,this.Ja)}function kb(a){return this.fromWireType(B[a>>2])}
function R(a,b,c,d){this.name=a;this.Ja=b;this.jb=c;this.eb=d;this.fb=!1;this.Pa=this.Mb=this.kb=this.qb=this.Qb=this.Kb=void 0;void 0!==b.Ma?this.toWireType=ib:(this.toWireType=d?gb:jb,this.Qa=null)}
var lb=(a,b,c)=>{if(!l.hasOwnProperty(a))throw new La("Replacing nonexistant public symbol");void 0!==l[a].Na&&void 0!==c?l[a].Na[c]=b:(l[a]=b,l[a].cb=c)},mb=(a,b)=>{var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=l["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=D.get(b).apply(null,c);return d}},S=(a,b)=>{a=N(a);var c=a.includes("j")?mb(a,b):D.get(b);if("function"!=typeof c)throw new O(`unknown function pointer with signature ${a}: ${b}`);
return c},nb=void 0,pb=a=>{a=ob(a);var b=N(a);T(a);return b},qb=(a,b)=>{function c(f){e[f]||K[f]||(Ka[f]?Ka[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new nb(`${a}: `+d.map(pb).join([", "]));},rb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(B[b+4*d>>2]);return c};
function sb(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=bb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function tb(a,b,c,d,e,f){var k=b.length;if(2>k)throw new O("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,m=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Qa){m=!0;break}var n="void"!==b[0].name,p="",r="";for(c=0;c<k-2;++c)p+=(0!==c?", ":"")+"arg"+c,r+=(0!==c?", ":"")+"arg"+c+"Wired";a=`\n        return function ${ab(a)}(${p}) {\n        if (arguments.length !== ${k-2}) {\n          throwBindingError('function ${a} called with ' + arguments.length + ' arguments, expected ${k-
2}');\n        }`;m&&(a+="var destructors = [];\n");var v=m?"destructors":"null";p="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[Na,d,e,Ia,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+v+", this);\n");for(c=0;c<k-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+v+", arg"+c+"); // "+b[c+2].name+"\n",p.push("argType"+c),d.push(b[c+2]);h&&(r="thisWired"+(0<r.length?", ":"")+r);a+=(n||f?"var rv = ":"")+"invoker(fn"+(0<r.length?", ":"")+r+");\n";if(m)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].Qa&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",p.push(f+"_dtor"),d.push(b[c].Qa));n&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");p.push(a+"}\n");return sb(p).apply(null,d)}function ub(){this.Sa=[void 0];this.pb=[]}
var U=new ub,vb=a=>{a>=U.Ya&&0===--U.get(a).rb&&U.ib(a)},V=a=>{if(!a)throw new O("Cannot use deleted val. handle = "+a);return U.get(a).value},Q=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return U.bb({rb:1,value:a})}},hb=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},wb=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(la[c>>2])};case 8:return function(c){return this.fromWireType(ma[c>>
3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},xb=(a,b,c)=>{switch(b){case 1:return c?d=>y[d>>0]:d=>z[d>>0];case 2:return c?d=>ja[d>>1]:d=>ka[d>>1];case 4:return c?d=>A[d>>2]:d=>B[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},yb=(a,b,c,d)=>{if(0<d){d=c+d-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}if(127>=f){if(c>=d)break;b[c++]=f}else{if(2047>=f){if(c+1>=d)break;
b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=d)break;b[c++]=224|f>>12}else{if(c+3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63}b[c++]=128|f>>6&63}b[c++]=128|f&63}}b[c]=0}},zb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ab="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,Bb=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ab)return Ab.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];
if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Cb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Db=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ka[c];)++c;c<<=1;if(32<c-a&&Cb)return Cb.decode(z.subarray(a,c));c="";for(d=0;!(d>=b/
2);++d){var e=ja[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Eb=(a,b,c)=>{void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ja[b>>1]=a.charCodeAt(e),b+=2;ja[b>>1]=0;return b-d},Fb=a=>2*a.length,Gb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=A[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Jb=(a,b,c)=>{void 0===c&&(c=2147483647);if(4>c)return 0;
var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}A[b>>2]=f;b+=4;if(b+4>c)break}A[b>>2]=0;return b-d},Kb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Lb=(a,b)=>{var c=K[a];if(void 0===c)throw a=b+" has unknown type "+pb(a),new O(a);return c},Mb={},Nb=a=>{var b=Mb[a];return void 0===b?N(a):b},Ob=[],Pb=()=>"object"==typeof globalThis?globalThis:Function("return this")(),
Qb=a=>{var b=Ob.length;Ob.push(a);return b},Rb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Lb(B[b+4*d>>2],"parameter "+d);return c},Sb=[],Tb=a=>{for(var b="",c=0;c<a;++c)b+=(0!==c?", ":"")+"arg"+c;var d="return function emval_allocator_"+a+"(constructor, argTypes, args) {\n  var HEAPU32 = getMemory();\n";for(c=0;c<a;++c)d+="var argType"+c+" = requireRegisteredType(HEAPU32[((argTypes)>>2)], 'parameter "+c+"');\nvar arg"+c+" = argType"+c+".readValueFromPointer(args);\nargs += argType"+c+"['argPackAdvance'];\nargTypes += 4;\n";
return(new Function("requireRegisteredType","Module","valueToHandle","getMemory",d+("var obj = new constructor("+b+");\nreturn valueToHandle(obj);\n}\n")))(Lb,l,Q,()=>B)},Ub={},Vb={},Xb=()=>{if(!Wb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Vb)void 0===Vb[b]?delete a[b]:a[b]=Vb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);
Wb=c}return Wb},Wb,Yb=[null,[],[]],Zb=a=>0===a%4&&(0!==a%100||0===a%400),$b=[31,29,31,30,31,30,31,31,30,31,30,31],ac=[31,28,31,30,31,30,31,31,30,31,30,31];function bc(a){var b=Array(zb(a)+1);yb(a,b,0,b.length);return b}
var cc=(a,b,c,d)=>{function e(g,q,u){for(g="number"==typeof g?g.toString():g||"";g.length<q;)g=u[0]+g;return g}function f(g,q){return e(g,q,"0")}function k(g,q){function u(I){return 0>I?-1:0<I?1:0}var C;0===(C=u(g.getFullYear()-q.getFullYear()))&&0===(C=u(g.getMonth()-q.getMonth()))&&(C=u(g.getDate()-q.getDate()));return C}function h(g){switch(g.getDay()){case 0:return new Date(g.getFullYear()-1,11,29);case 1:return g;case 2:return new Date(g.getFullYear(),0,3);case 3:return new Date(g.getFullYear(),
0,2);case 4:return new Date(g.getFullYear(),0,1);case 5:return new Date(g.getFullYear()-1,11,31);case 6:return new Date(g.getFullYear()-1,11,30)}}function m(g){var q=g.Ua;for(g=new Date((new Date(g.Va+1900,0,1)).getTime());0<q;){var u=g.getMonth(),C=(Zb(g.getFullYear())?$b:ac)[u];if(q>C-g.getDate())q-=C-g.getDate()+1,g.setDate(1),11>u?g.setMonth(u+1):(g.setMonth(0),g.setFullYear(g.getFullYear()+1));else{g.setDate(g.getDate()+q);break}}u=new Date(g.getFullYear()+1,0,4);q=h(new Date(g.getFullYear(),
0,4));u=h(u);return 0>=k(q,g)?0>=k(u,g)?g.getFullYear()+1:g.getFullYear():g.getFullYear()-1}var n=B[d+40>>2];d={Tb:A[d>>2],Sb:A[d+4>>2],gb:A[d+8>>2],lb:A[d+12>>2],hb:A[d+16>>2],Va:A[d+20>>2],Ra:A[d+24>>2],Ua:A[d+28>>2],Wb:A[d+32>>2],Rb:A[d+36>>2],Ub:n?n?Bb(z,n):"":""};c=c?Bb(z,c):"";n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in n)c=c.replace(new RegExp(p,"g"),n[p]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),v="January February March April May June July August September October November December".split(" ");n={"%a":g=>r[g.Ra].substring(0,3),"%A":g=>r[g.Ra],"%b":g=>v[g.hb].substring(0,3),"%B":g=>v[g.hb],"%C":g=>f((g.Va+1900)/
100|0,2),"%d":g=>f(g.lb,2),"%e":g=>e(g.lb,2," "),"%g":g=>m(g).toString().substring(2),"%G":g=>m(g),"%H":g=>f(g.gb,2),"%I":g=>{g=g.gb;0==g?g=12:12<g&&(g-=12);return f(g,2)},"%j":g=>{for(var q=0,u=0;u<=g.hb-1;q+=(Zb(g.Va+1900)?$b:ac)[u++]);return f(g.lb+q,3)},"%m":g=>f(g.hb+1,2),"%M":g=>f(g.Sb,2),"%n":()=>"\n","%p":g=>0<=g.gb&&12>g.gb?"AM":"PM","%S":g=>f(g.Tb,2),"%t":()=>"\t","%u":g=>g.Ra||7,"%U":g=>f(Math.floor((g.Ua+7-g.Ra)/7),2),"%V":g=>{var q=Math.floor((g.Ua+7-(g.Ra+6)%7)/7);2>=(g.Ra+371-g.Ua-
2)%7&&q++;if(q)53==q&&(u=(g.Ra+371-g.Ua)%7,4==u||3==u&&Zb(g.Va)||(q=1));else{q=52;var u=(g.Ra+7-g.Ua-1)%7;(4==u||5==u&&Zb(g.Va%400-1))&&q++}return f(q,2)},"%w":g=>g.Ra,"%W":g=>f(Math.floor((g.Ua+7-(g.Ra+6)%7)/7),2),"%y":g=>(g.Va+1900).toString().substring(2),"%Y":g=>g.Va+1900,"%z":g=>{g=g.Rb;var q=0<=g;g=Math.abs(g)/60;return(q?"+":"-")+String("0000"+(g/60*100+g%60)).slice(-4)},"%Z":g=>g.Ub,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(p in n)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),n[p](d)));
c=c.replace(/\0\0/g,"%");p=bc(c);if(p.length>b)return 0;y.set(p,a);return p.length-1};La=l.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var dc=Array(256),ec=0;256>ec;++ec)dc[ec]=String.fromCharCode(ec);Ma=dc;O=l.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
P.prototype.isAliasOf=function(a){if(!(this instanceof P&&a instanceof P))return!1;var b=this.Ha.Ka.Ja,c=this.Ha.Ia,d=a.Ha.Ka.Ja;for(a=a.Ha.Ia;b.Ma;)c=b.ab(c),b=b.Ma;for(;d.Ma;)a=d.ab(a),d=d.Ma;return b===d&&c===a};
P.prototype.clone=function(){this.Ha.Ia||Pa(this);if(this.Ha.$a)return this.Ha.count.value+=1,this;var a=Za,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Ha;a=a(c.call(b,d,{Ha:{value:{count:e.count,Wa:e.Wa,$a:e.$a,Ia:e.Ia,Ka:e.Ka,La:e.La,Oa:e.Oa}}}));a.Ha.count.value+=1;a.Ha.Wa=!1;return a};
P.prototype["delete"]=function(){this.Ha.Ia||Pa(this);if(this.Ha.Wa&&!this.Ha.$a)throw new O("Object already scheduled for deletion");Ra(this);var a=this.Ha;--a.count.value;0===a.count.value&&(a.La?a.Oa.Pa(a.La):a.Ka.Ja.Pa(a.Ia));this.Ha.$a||(this.Ha.La=void 0,this.Ha.Ia=void 0)};P.prototype.isDeleted=function(){return!this.Ha.Ia};
P.prototype.deleteLater=function(){this.Ha.Ia||Pa(this);if(this.Ha.Wa&&!this.Ha.$a)throw new O("Object already scheduled for deletion");Ua.push(this);1===Ua.length&&Wa&&Wa(Va);this.Ha.Wa=!0;return this};l.getInheritedInstanceCount=()=>Object.keys(Xa).length;l.getLiveInheritedInstances=()=>{var a=[],b;for(b in Xa)Xa.hasOwnProperty(b)&&a.push(Xa[b]);return a};l.flushPendingDeletes=Va;l.setDelayFunction=a=>{Wa=a;Ua.length&&Wa&&Wa(Va)};R.prototype.Db=function(a){this.qb&&(a=this.qb(a));return a};
R.prototype.nb=function(a){this.Pa&&this.Pa(a)};R.prototype.argPackAdvance=8;R.prototype.readValueFromPointer=kb;R.prototype.deleteObject=a=>{if(null!==a)a["delete"]()};
R.prototype.fromWireType=function(a){function b(){return this.fb?$a(this.Ja.Xa,{Ka:this.Kb,Ia:c,Oa:this,La:a}):$a(this.Ja.Xa,{Ka:this,Ia:a})}var c=this.Db(a);if(!c)return this.nb(a),null;var d=Ya(this.Ja,c);if(void 0!==d){if(0===d.Ha.count.value)return d.Ha.Ia=c,d.Ha.La=a,d.clone();d=d.clone();this.nb(a);return d}d=this.Ja.Cb(c);d=Ta[d];if(!d)return b.call(this);d=this.eb?d.zb:d.pointerType;var e=Sa(c,this.Ja,d.Ja);return null===e?b.call(this):this.fb?$a(d.Ja.Xa,{Ka:d,Ia:e,Oa:this,La:a}):$a(d.Ja.Xa,
{Ka:d,Ia:e})};nb=l.UnboundTypeError=((a,b)=>{var c=bb(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
Object.assign(ub.prototype,{get(a){return this.Sa[a]},has(a){return void 0!==this.Sa[a]},bb(a){var b=this.pb.pop()||this.Sa.length;this.Sa[b]=a;return b},ib(a){this.Sa[a]=void 0;this.pb.push(a)}});U.Sa.push({value:void 0},{value:null},{value:!0},{value:!1});U.Ya=U.Sa.length;l.count_emval_handles=()=>{for(var a=0,b=U.Ya;b<U.Sa.length;++b)void 0!==U.Sa[b]&&++a;return a};
var Cc={s:a=>{a=new Ca(a);a.ub()||(a.sb(!0),Ba--);a.tb(!1);Aa.push(a);fc(a.Za);return a.vb()},v:()=>{W(0,0);var a=Aa.pop();gc(a.Za);H=0},a:()=>Ga([]),j:a=>Ga([a]),O:()=>{var a=Aa.pop();a||fa("no exception to throw");var b=a.Za;a.Eb()||(Aa.push(a),a.tb(!0),a.sb(!1),Ba++);H=b;throw H;},u:(a,b,c)=>{(new Ca(a)).wb(b,c);H=a;Ba++;throw H;},aa:()=>Ba,e:a=>{H||(H=a);throw H;},la:a=>{var b=Ha[a];delete Ha[a];var c=b.kb,d=b.Pa,e=b.ob,f=e.map(k=>k.Hb).concat(e.map(k=>k.Ob));M([a],f,k=>{var h={};e.forEach((m,
n)=>{var p=k[n],r=m.Fb,v=m.Gb,g=k[n+e.length],q=m.Nb,u=m.Pb;h[m.Bb]={read:C=>p.fromWireType(r(v,C)),write:(C,I)=>{var G=[];q(u,C,g.toWireType(G,I));Ia(G)}}});return[{name:b.name,fromWireType:m=>{var n={},p;for(p in h)n[p]=h[p].read(m);d(m);return n},toWireType:(m,n)=>{for(var p in h)if(!(p in n))throw new TypeError(`Missing field: "${p}"`);var r=c();for(p in h)h[p].write(r,n[p]);null!==m&&m.push(d,r);return r},argPackAdvance:8,readValueFromPointer:Ja,Qa:d}]})},T:()=>{},da:(a,b,c,d)=>{b=N(b);L(a,{name:b,
fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(z[e])},Qa:null})},J:(a,b,c,d,e,f,k,h,m,n,p,r,v)=>{p=N(p);f=S(e,f);h&&(h=S(k,h));n&&(n=S(m,n));v=S(r,v);var g=ab(p);db(g,function(){qb(`Cannot construct ${p} due to unbound types`,[d])});M([a,b,c],d?[d]:[],function(q){q=q[0];if(d){var u=q.Ja;var C=u.Xa}else C=P.prototype;q=bb(g,function(){if(Object.getPrototypeOf(this)!==I)throw new O("Use 'new' to construct "+
p);if(void 0===G.Ta)throw new O(p+" has no accessible constructor");var Hb=G.Ta[arguments.length];if(void 0===Hb)throw new O(`Tried to invoke ctor of ${p} with invalid number of parameters (${arguments.length}) - expected (${Object.keys(G.Ta).toString()}) parameters instead!`);return Hb.apply(this,arguments)});var I=Object.create(C,{constructor:{value:q}});q.prototype=I;var G=new eb(p,q,I,v,u,f,h,n);G.Ma&&(void 0===G.Ma.mb&&(G.Ma.mb=[]),G.Ma.mb.push(G));u=new R(p,G,!0,!1);C=new R(p+"*",G,!1,!1);var Ib=
new R(p+" const*",G,!1,!0);Ta[a]={pointerType:C,zb:Ib};lb(g,q);return[u,C,Ib]})},H:(a,b,c,d,e,f)=>{var k=rb(b,c);e=S(d,e);M([],[a],function(h){h=h[0];var m=`constructor ${h.name}`;void 0===h.Ja.Ta&&(h.Ja.Ta=[]);if(void 0!==h.Ja.Ta[b-1])throw new O(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.Ja.Ta[b-1]=()=>{qb(`Cannot construct ${h.name} due to unbound types`,
k)};M([],k,n=>{n.splice(1,0,null);h.Ja.Ta[b-1]=tb(m,n,null,e,f);return[]});return[]})},n:(a,b,c,d,e,f,k,h,m)=>{var n=rb(c,d);b=N(b);f=S(e,f);M([],[a],function(p){function r(){qb(`Cannot call ${v} due to unbound types`,n)}p=p[0];var v=`${p.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&p.Ja.Lb.push(b);var g=p.Ja.Xa,q=g[b];void 0===q||void 0===q.Na&&q.className!==p.name&&q.cb===c-2?(r.cb=c-2,r.className=p.name,g[b]=r):(cb(g,b,v),g[b].Na[c-2]=r);M([],n,function(u){u=tb(v,u,p,f,k,m);void 0===
g[b].Na?(u.cb=c-2,g[b]=u):g[b].Na[c-2]=u;return[]});return[]})},ca:(a,b)=>{b=N(b);L(a,{name:b,fromWireType:c=>{var d=V(c);vb(c);return d},toWireType:(c,d)=>Q(d),argPackAdvance:8,readValueFromPointer:Ja,Qa:null})},L:(a,b,c)=>{b=N(b);L(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:wb(b,c),Qa:null})},B:(a,b,c,d,e,f,k)=>{var h=rb(b,c);a=N(a);e=S(d,e);db(a,function(){qb(`Cannot call ${a} due to unbound types`,h)},b-1);M([],h,function(m){lb(a,tb(a,[m[0],null].concat(m.slice(1)),
null,e,f,k),b-1);return[]})},p:(a,b,c,d,e)=>{b=N(b);-1===e&&(e=4294967295);e=h=>h;if(0===d){var f=32-8*c;e=h=>h<<f>>>f}var k=b.includes("unsigned")?function(h,m){return m>>>0}:function(h,m){return m};L(a,{name:b,fromWireType:e,toWireType:k,argPackAdvance:8,readValueFromPointer:xb(b,c,0!==d),Qa:null})},m:(a,b,c)=>{function d(f){return new e(y.buffer,B[f+4>>2],B[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=N(c);L(a,{name:c,fromWireType:d,
argPackAdvance:8,readValueFromPointer:d},{Ib:!0})},M:(a,b)=>{b=N(b);var c="std::string"===b;L(a,{name:b,fromWireType:d=>{var e=B[d>>2],f=d+4;if(c)for(var k=f,h=0;h<=e;++h){var m=f+h;if(h==e||0==z[m]){k=k?Bb(z,k,m-k):"";if(void 0===n)var n=k;else n+=String.fromCharCode(0),n+=k;k=m+1}}else{n=Array(e);for(h=0;h<e;++h)n[h]=String.fromCharCode(z[f+h]);n=n.join("")}T(d);return n},toWireType:(d,e)=>{e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||
e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new O("Cannot pass non-string to std::string");var k=c&&f?zb(e):e.length;var h=hc(4+k+1),m=h+4;B[h>>2]=k;if(c&&f)yb(e,z,m,k+1);else if(f)for(f=0;f<k;++f){var n=e.charCodeAt(f);if(255<n)throw T(m),new O("String has UTF-16 code units that do not fit in 8 bits");z[m+f]=n}else for(f=0;f<k;++f)z[m+f]=e[f];null!==d&&d.push(T,h);return h},argPackAdvance:8,readValueFromPointer:kb,Qa:d=>T(d)})},E:(a,b,c)=>{c=N(c);if(2===b){var d=Db;var e=Eb;var f=
Fb;var k=()=>ka;var h=1}else 4===b&&(d=Gb,e=Jb,f=Kb,k=()=>B,h=2);L(a,{name:c,fromWireType:m=>{for(var n=B[m>>2],p=k(),r,v=m+4,g=0;g<=n;++g){var q=m+4+g*b;if(g==n||0==p[q>>h])v=d(v,q-v),void 0===r?r=v:(r+=String.fromCharCode(0),r+=v),v=q+b}T(m);return r},toWireType:(m,n)=>{if("string"!=typeof n)throw new O(`Cannot pass non-string to C++ string type ${c}`);var p=f(n),r=hc(4+p+b);B[r>>2]=p>>h;e(n,r+4,p+b);null!==m&&m.push(T,r);return r},argPackAdvance:8,readValueFromPointer:Ja,Qa:m=>T(m)})},Q:(a,b,c,
d,e,f)=>{Ha[a]={name:N(b),kb:S(c,d),Pa:S(e,f),ob:[]}},C:(a,b,c,d,e,f,k,h,m,n)=>{Ha[a].ob.push({Bb:N(b),Hb:c,Fb:S(d,e),Gb:f,Ob:k,Nb:S(h,m),Pb:n})},ea:(a,b)=>{b=N(b);L(a,{Jb:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},ga:(a,b,c)=>{a=V(a);b=Lb(b,"emval::as");var d=[],e=Q(d);B[c>>2]=e;return b.toWireType(d,a)},ia:(a,b,c,d,e)=>{a=Ob[a];b=V(b);c=Nb(c);var f=[];B[d>>2]=Q(f);return a(b,c,f,e)},N:(a,b,c,d)=>{a=Ob[a];b=V(b);c=Nb(c);a(b,c,null,d)},K:vb,ka:a=>{if(0===a)return Q(Pb());
a=Nb(a);return Q(Pb()[a])},P:(a,b)=>{var c=Rb(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(p){return p.name}).join("_")+"$";var e=Sb[b];if(void 0!==e)return e;e=["retType"];for(var f=[d],k="",h=0;h<a-1;++h)k+=(0!==h?", ":"")+"arg"+h,e.push("argType"+h),f.push(c[1+h]);var m="return function "+ab("methodCaller_"+b)+"(handle, name, destructors, args) {\n",n=0;for(h=0;h<a-1;++h)m+="    var arg"+h+" = argType"+h+".readValueFromPointer(args"+(n?"+"+n:"")+");\n",n+=c[h+1].argPackAdvance;m+="    var rv = handle[name]("+
k+");\n";for(h=0;h<a-1;++h)c[h+1].deleteObject&&(m+="    argType"+h+".deleteObject(arg"+h+");\n");d.Jb||(m+="    return retType.toWireType(destructors, rv);\n");e.push(m+"};\n");a=sb(e).apply(null,f);e=Qb(a);return Sb[b]=e},A:a=>{a=Nb(a);return Q(l[a])},ja:(a,b)=>{a=V(a);b=V(b);return Q(a[b])},w:a=>{4<a&&(U.get(a).rb+=1)},fa:(a,b,c,d)=>{a=V(a);var e=Ub[b];e||(e=Tb(b),Ub[b]=e);return e(a,c,d)},F:a=>Q(Nb(a)),ha:a=>{var b=V(a);Ia(b);vb(a)},G:(a,b)=>{a=Lb(a,"_emval_take_value");a=a.readValueFromPointer(b);
return Q(a)},D:()=>{fa("")},ba:()=>{fa("OOM")},X:(a,b)=>{var c=0;Xb().forEach((d,e)=>{var f=b+c;e=B[a+4*e>>2]=f;for(f=0;f<d.length;++f)y[e++>>0]=d.charCodeAt(f);y[e>>0]=0;c+=d.length+1});return 0},Y:(a,b)=>{var c=Xb();B[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);B[b>>2]=d;return 0},Z:()=>52,$:()=>52,S:function(){return 70},_:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var k=B[b>>2],h=B[b+4>>2];b+=8;for(var m=0;m<h;m++){var n=z[k+m],p=Yb[a];0===n||10===n?((1===a?ea:w)(Bb(p,0)),p.length=0):p.push(n)}e+=
h}B[d>>2]=e;return 0},V:ic,U:jc,b:kc,d:lc,r:mc,k:nc,l:oc,o:pc,I:qc,y:rc,R:sc,i:tc,f:uc,c:vc,g:wc,h:xc,z:yc,q:zc,t:Ac,x:Bc,W:(a,b,c,d)=>cc(a,b,c,d)},X=function(){function a(c){X=c=c.exports;ha=X.ma;var d=ha.buffer;l.HEAP8=y=new Int8Array(d);l.HEAP16=ja=new Int16Array(d);l.HEAPU8=z=new Uint8Array(d);l.HEAPU16=ka=new Uint16Array(d);l.HEAP32=A=new Int32Array(d);l.HEAPU32=B=new Uint32Array(d);l.HEAPF32=la=new Float32Array(d);l.HEAPF64=ma=new Float64Array(d);D=X.ra;oa.unshift(X.na);E--;l.monitorRunDependencies&&
l.monitorRunDependencies(E);0==E&&(null!==ra&&(clearInterval(ra),ra=null),sa&&(d=sa,sa=null,d()));return c}var b={a:Cc};E++;l.monitorRunDependencies&&l.monitorRunDependencies(E);if(l.instantiateWasm)try{return l.instantiateWasm(b,a)}catch(c){w(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}ya(b,function(c){a(c.instance)}).catch(ba);return{}}(),hc=a=>(hc=X.oa)(a),ob=a=>(ob=X.pa)(a);l.__embind_initialize_bindings=()=>(l.__embind_initialize_bindings=X.qa)();
var T=a=>(T=X.sa)(a),W=(a,b)=>(W=X.ta)(a,b),Ea=a=>(Ea=X.ua)(a),Y=()=>(Y=X.va)(),Z=a=>(Z=X.wa)(a),gc=a=>(gc=X.xa)(a),fc=a=>(fc=X.ya)(a),Fa=(a,b,c)=>(Fa=X.za)(a,b,c),Da=a=>(Da=X.Aa)(a),Dc=l.dynCall_iiij=(a,b,c,d,e)=>(Dc=l.dynCall_iiij=X.Ba)(a,b,c,d,e);l.dynCall_viijii=(a,b,c,d,e,f,k)=>(l.dynCall_viijii=X.Ca)(a,b,c,d,e,f,k);l.dynCall_jiji=(a,b,c,d,e)=>(l.dynCall_jiji=X.Da)(a,b,c,d,e);l.dynCall_iiiiij=(a,b,c,d,e,f,k)=>(l.dynCall_iiiiij=X.Ea)(a,b,c,d,e,f,k);
l.dynCall_iiiiijj=(a,b,c,d,e,f,k,h,m)=>(l.dynCall_iiiiijj=X.Fa)(a,b,c,d,e,f,k,h,m);l.dynCall_iiiiiijj=(a,b,c,d,e,f,k,h,m,n)=>(l.dynCall_iiiiiijj=X.Ga)(a,b,c,d,e,f,k,h,m,n);function lc(a,b,c){var d=Y();try{return D.get(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function kc(a,b){var c=Y();try{return D.get(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function vc(a,b,c){var d=Y();try{D.get(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}
function nc(a,b,c,d){var e=Y();try{return D.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function oc(a,b,c,d,e){var f=Y();try{return D.get(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0)throw k;W(1,0)}}function tc(a){var b=Y();try{D.get(a)()}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}function xc(a,b,c,d,e){var f=Y();try{D.get(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0)throw k;W(1,0)}}function mc(a,b,c,d){var e=Y();try{return D.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}
function wc(a,b,c,d){var e=Y();try{D.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function Ac(a,b,c,d,e,f,k,h,m,n,p){var r=Y();try{D.get(a)(b,c,d,e,f,k,h,m,n,p)}catch(v){Z(r);if(v!==v+0)throw v;W(1,0)}}function uc(a,b){var c=Y();try{D.get(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function ic(a,b,c,d,e,f){var k=Y();try{return D.get(a)(b,c,d,e,f)}catch(h){Z(k);if(h!==h+0)throw h;W(1,0)}}
function yc(a,b,c,d,e,f){var k=Y();try{D.get(a)(b,c,d,e,f)}catch(h){Z(k);if(h!==h+0)throw h;W(1,0)}}function pc(a,b,c,d,e,f,k){var h=Y();try{return D.get(a)(b,c,d,e,f,k)}catch(m){Z(h);if(m!==m+0)throw m;W(1,0)}}function qc(a,b,c,d,e,f,k,h){var m=Y();try{return D.get(a)(b,c,d,e,f,k,h)}catch(n){Z(m);if(n!==n+0)throw n;W(1,0)}}function zc(a,b,c,d,e,f,k,h){var m=Y();try{D.get(a)(b,c,d,e,f,k,h)}catch(n){Z(m);if(n!==n+0)throw n;W(1,0)}}
function rc(a,b,c,d,e,f,k,h,m,n,p,r){var v=Y();try{return D.get(a)(b,c,d,e,f,k,h,m,n,p,r)}catch(g){Z(v);if(g!==g+0)throw g;W(1,0)}}function Bc(a,b,c,d,e,f,k,h,m,n,p,r,v,g,q,u){var C=Y();try{D.get(a)(b,c,d,e,f,k,h,m,n,p,r,v,g,q,u)}catch(I){Z(C);if(I!==I+0)throw I;W(1,0)}}function jc(a){var b=Y();try{return D.get(a)()}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}function sc(a,b,c,d,e){var f=Y();try{return Dc(a,b,c,d,e)}catch(k){Z(f);if(k!==k+0)throw k;W(1,0)}}var Ec;sa=function Fc(){Ec||Gc();Ec||(sa=Fc)};
function Gc(){function a(){if(!Ec&&(Ec=!0,l.calledRun=!0,!ia)){za(oa);aa(l);if(l.onRuntimeInitialized)l.onRuntimeInitialized();if(l.postRun)for("function"==typeof l.postRun&&(l.postRun=[l.postRun]);l.postRun.length;){var b=l.postRun.shift();pa.unshift(b)}za(pa)}}if(!(0<E)){if(l.preRun)for("function"==typeof l.preRun&&(l.preRun=[l.preRun]);l.preRun.length;)qa();za(na);0<E||(l.setStatus?(l.setStatus("Running..."),setTimeout(function(){setTimeout(function(){l.setStatus("")},1);a()},1)):a())}}
if(l.preInit)for("function"==typeof l.preInit&&(l.preInit=[l.preInit]);0<l.preInit.length;)l.preInit.pop()();Gc();


  return moduleArg.ready
}

);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = MeshUtility;
else if (typeof define === 'function' && define['amd'])
  define([], () => MeshUtility);
