
var MeshUtility = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(moduleArg = {}) {

var k=moduleArg,aa,ba;k.ready=new Promise((a,b)=>{aa=a;ba=b});var ca=Object.assign({},k),da="./this.program",r="";"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src);_scriptDir&&(r=_scriptDir);0!==r.indexOf("blob:")?r=r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1):r="";var ea=k.print||console.log.bind(console),v=k.printErr||console.error.bind(console);Object.assign(k,ca);ca=null;k.thisProgram&&(da=k.thisProgram);var y;k.wasmBinary&&(y=k.wasmBinary);
var noExitRuntime=k.noExitRuntime||!0;"object"!=typeof WebAssembly&&fa("no native wasm support detected");var ha,ia=!1,z,A,C,ja,D,E,ka,la,ma,na=[],oa=[],pa=[],qa=!1;function ra(){var a=k.preRun.shift();na.unshift(a)}var F=0,sa=null,G=null;function fa(a){if(k.onAbort)k.onAbort(a);a="Aborted("+a+")";v(a);ia=!0;a+=". Build with -sASSERTIONS for more info.";qa&&ta();a=new WebAssembly.RuntimeError(a);ba(a);throw a;}function ua(a){return a.startsWith("data:application/octet-stream;base64,")}var H;H="MeshUtility.wasm";
if(!ua(H)){var va=H;H=k.locateFile?k.locateFile(va,r):r+va}function wa(a){if(a==H&&y)return new Uint8Array(y);throw"both async and sync fetching of the wasm failed";}function xa(a){return y||"function"!=typeof fetch?Promise.resolve().then(()=>wa(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>wa(a))}
function ya(a,b,c){return xa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{v(`failed to asynchronously prepare wasm: ${d}`);fa(d)})}function za(a,b){var c=H;return y||"function"!=typeof WebAssembly.instantiateStreaming||ua(c)||"function"!=typeof fetch?ya(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){v(`wasm streaming compile failed: ${e}`);v("falling back to ArrayBuffer instantiation");return ya(c,a,b)}))}
var Aa=a=>{for(;0<a.length;)a.shift()(k)},Ba={},Ca=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Da(a){return this.fromWireType(D[a>>2])}
var I={},J={},Ea={},K=void 0,N=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new K("Mismatched type converter count");for(var l=0;l<a.length;++l)L(a[l],h[l])}a.forEach(function(h){Ea[h]=b});var e=Array(b.length),g=[],m=0;b.forEach((h,l)=>{J.hasOwnProperty(h)?e[l]=J[h]:(g.push(h),I.hasOwnProperty(h)||(I[h]=[]),I[h].push(()=>{e[l]=J[h];++m;m===g.length&&d(e)}))});0===g.length&&d(e)},Fa=void 0,O=a=>{for(var b="";A[a];)b+=Fa[A[a++]];return b},P=void 0,Ga=a=>{throw new P(a);};
function Ha(a,b,c={}){var d=b.name;if(!a)throw new P(`type "${d}" must have a positive integer typeid pointer`);if(J.hasOwnProperty(a)){if(c.Qa)return;throw new P(`Cannot register type '${d}' twice`);}J[a]=b;delete Ea[a];I.hasOwnProperty(a)&&(b=I[a],delete I[a],b.forEach(e=>e()))}function L(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");Ha(a,b,c)}
var Ia=a=>{throw new P(a.Z.ba.$.name+" instance already deleted");},Ja=!1,Ka=()=>{},La=(a,b,c)=>{if(b===c)return a;if(void 0===c.da)return null;a=La(a,b,c.da);return null===a?null:c.Ja(a)},Ma={},Q=[],Na=()=>{for(;Q.length;){var a=Q.pop();a.Z.na=!1;a["delete"]()}},R=void 0,Oa={},Pa=(a,b)=>{if(void 0===b)throw new P("ptr should not be undefined");for(;a.da;)b=a.qa(b),a=a.da;return Oa[b]},Ra=(a,b)=>{if(!b.ba||!b.aa)throw new K("makeClassHandle requires ptr and ptrType");if(!!b.fa!==!!b.ca)throw new K("Both smartPtrType and smartPtr must be specified");
b.count={value:1};return Qa(Object.create(a,{Z:{value:b}}))},Qa=a=>{if("undefined"===typeof FinalizationRegistry)return Qa=b=>b,a;Ja=new FinalizationRegistry(b=>{b=b.Z;--b.count.value;0===b.count.value&&(b.ca?b.fa.ga(b.ca):b.ba.$.ga(b.aa))});Qa=b=>{var c=b.Z;c.ca&&Ja.register(b,{Z:c},b);return b};Ka=b=>{Ja.unregister(b)};return Qa(a)};function S(){}var Sa=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};
function Ta(a,b){a=Sa(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
var Ua=(a,b,c)=>{if(void 0===a[b].ea){var d=a[b];a[b]=function(){if(!a[b].ea.hasOwnProperty(arguments.length))throw new P(`Function '${c}' called with an invalid number of arguments (${arguments.length}) - expects one of (${a[b].ea})!`);return a[b].ea[arguments.length].apply(this,arguments)};a[b].ea=[];a[b].ea[d.ra]=d}},Va=(a,b,c)=>{if(k.hasOwnProperty(a)){if(void 0===c||void 0!==k[a].ea&&void 0!==k[a].ea[c])throw new P(`Cannot register public name '${a}' twice`);Ua(k,a,a);if(k.hasOwnProperty(c))throw new P(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
k[a].ea[c]=b}else k[a]=b,void 0!==c&&(k[a].cb=c)};function Wa(a,b,c,d,e,g,m,h){this.name=a;this.constructor=b;this.oa=c;this.ga=d;this.da=e;this.La=g;this.qa=m;this.Ja=h;this.Ta=[]}var Xa=(a,b,c)=>{for(;b!==c;){if(!b.qa)throw new P(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.qa(a);b=b.da}return a};
function Ya(a,b){if(null===b){if(this.wa)throw new P(`null is not a valid ${this.name}`);return 0}if(!b.Z)throw new P(`Cannot pass "${Za(b)}" as a ${this.name}`);if(!b.Z.aa)throw new P(`Cannot pass deleted object as a pointer of type ${this.name}`);return Xa(b.Z.aa,b.Z.ba.$,this.$)}
function $a(a,b){if(null===b){if(this.wa)throw new P(`null is not a valid ${this.name}`);if(this.ta){var c=this.xa();null!==a&&a.push(this.ga,c);return c}return 0}if(!b.Z)throw new P(`Cannot pass "${Za(b)}" as a ${this.name}`);if(!b.Z.aa)throw new P(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.sa&&b.Z.ba.sa)throw new P(`Cannot convert argument of type ${b.Z.fa?b.Z.fa.name:b.Z.ba.name} to parameter type ${this.name}`);c=Xa(b.Z.aa,b.Z.ba.$,this.$);if(this.ta){if(void 0===
b.Z.ca)throw new P("Passing raw pointer to smart pointer is illegal");switch(this.Ya){case 0:if(b.Z.fa===this)c=b.Z.ca;else throw new P(`Cannot convert argument of type ${b.Z.fa?b.Z.fa.name:b.Z.ba.name} to parameter type ${this.name}`);break;case 1:c=b.Z.ca;break;case 2:if(b.Z.fa===this)c=b.Z.ca;else{var d=b.clone();c=this.Ua(c,T(()=>d["delete"]()));null!==a&&a.push(this.ga,c)}break;default:throw new P("Unsupporting sharing policy");}}return c}
function ab(a,b){if(null===b){if(this.wa)throw new P(`null is not a valid ${this.name}`);return 0}if(!b.Z)throw new P(`Cannot pass "${Za(b)}" as a ${this.name}`);if(!b.Z.aa)throw new P(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.Z.ba.sa)throw new P(`Cannot convert argument of type ${b.Z.ba.name} to parameter type ${this.name}`);return Xa(b.Z.aa,b.Z.ba.$,this.$)}function bb(a){return this.fromWireType(E[a>>2])}
function U(a,b,c,d){this.name=a;this.$=b;this.wa=c;this.sa=d;this.ta=!1;this.ga=this.Ua=this.xa=this.Ea=this.Ya=this.Sa=void 0;void 0!==b.da?this.toWireType=$a:(this.toWireType=d?Ya:ab,this.ha=null)}
var cb=(a,b,c)=>{if(!k.hasOwnProperty(a))throw new K("Replacing nonexistant public symbol");void 0!==k[a].ea&&void 0!==c?k[a].ea[c]=b:(k[a]=b,k[a].ra=c)},db=(a,b)=>{var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=k["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=ma.get(b).apply(null,c);return d}},V=(a,b)=>{a=O(a);var c=a.includes("j")?db(a,b):ma.get(b);if("function"!=typeof c)throw new P(`unknown function pointer with signature ${a}: ${b}`);
return c},eb=void 0,gb=a=>{a=fb(a);var b=O(a);W(a);return b},hb=(a,b)=>{function c(g){e[g]||J[g]||(Ea[g]?Ea[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new eb(`${a}: `+d.map(gb).join([", "]));},ib=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(E[b+4*d>>2]);return c};
function jb(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Ta(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function kb(a,b,c,d,e,g){var m=b.length;if(2>m)throw new P("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].ha){l=!0;break}var n="void"!==b[0].name,p="",u="";for(c=0;c<m-2;++c)p+=(0!==c?", ":"")+"arg"+c,u+=(0!==c?", ":"")+"arg"+c+"Wired";a=`\n        return function ${Sa(a)}(${p}) {\n        if (arguments.length !== ${m-2}) {\n          throwBindingError('function ${a} called with ' + arguments.length + ' arguments, expected ${m-
2}');\n        }`;l&&(a+="var destructors = [];\n");var w=l?"destructors":"null";p="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[Ga,d,e,Ca,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+w+", this);\n");for(c=0;c<m-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+w+", arg"+c+"); // "+b[c+2].name+"\n",p.push("argType"+c),d.push(b[c+2]);h&&(u="thisWired"+(0<u.length?", ":"")+u);a+=(n||g?"var rv = ":"")+"invoker(fn"+(0<u.length?", ":"")+u+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)g=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].ha&&(a+=g+"_dtor("+g+"); // "+b[c].name+"\n",p.push(g+"_dtor"),d.push(b[c].ha));n&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");p.push(a+"}\n");return jb(p).apply(null,d)}function lb(){this.ja=[void 0];this.Da=[]}
var X=new lb,mb=a=>{a>=X.za&&0===--X.get(a).Fa&&X.Ha(a)},Y=a=>{if(!a)throw new P("Cannot use deleted val. handle = "+a);return X.get(a).value},T=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return X.Ga({Fa:1,value:a})}},Za=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},nb=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ka[c>>2])};case 8:return function(c){return this.fromWireType(la[c>>
3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},ob=(a,b,c)=>{switch(b){case 1:return c?d=>z[d>>0]:d=>A[d>>0];case 2:return c?d=>C[d>>1]:d=>ja[d>>1];case 4:return c?d=>D[d>>2]:d=>E[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},pb=(a,b,c,d)=>{if(0<d){d=c+d-1;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var m=a.charCodeAt(++e);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;
b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0}},qb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},rb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,sb=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&rb)return rb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];
if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var m=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|m:(e&7)<<18|g<<12|m<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},tb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,ub=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ja[c];)++c;c<<=1;if(32<c-a&&tb)return tb.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/
2);++d){var e=C[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},vb=(a,b,c)=>{void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)C[b>>1]=a.charCodeAt(e),b+=2;C[b>>1]=0;return b-d},yb=a=>2*a.length,zb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=D[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Ab=(a,b,c)=>{void 0===c&&(c=2147483647);if(4>c)return 0;var d=
b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var m=a.charCodeAt(++e);g=65536+((g&1023)<<10)|m&1023}D[b>>2]=g;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d},Bb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Cb=(a,b)=>{var c=J[a];if(void 0===c)throw a=b+" has unknown type "+gb(a),new P(a);return c},Db={},Eb=a=>{var b=Db[a];return void 0===b?O(a):b},Fb=[],Gb=()=>"object"==typeof globalThis?globalThis:Function("return this")(),
Hb=a=>{var b=Fb.length;Fb.push(a);return b},Ib=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Cb(E[b+4*d>>2],"parameter "+d);return c},Jb=[],Kb=a=>{for(var b="",c=0;c<a;++c)b+=(0!==c?", ":"")+"arg"+c;var d="return function emval_allocator_"+a+"(constructor, argTypes, args) {\n  var HEAPU32 = getMemory();\n";for(c=0;c<a;++c)d+="var argType"+c+" = requireRegisteredType(HEAPU32[((argTypes)>>2)], 'parameter "+c+"');\nvar arg"+c+" = argType"+c+".readValueFromPointer(args);\nargs += argType"+c+"['argPackAdvance'];\nargTypes += 4;\n";
return(new Function("requireRegisteredType","Module","valueToHandle","getMemory",d+("var obj = new constructor("+b+");\nreturn valueToHandle(obj);\n}\n")))(Cb,k,T,()=>E)},Lb={},Mb={},Ob=()=>{if(!Nb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Mb)void 0===Mb[b]?delete a[b]:a[b]=Mb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);
Nb=c}return Nb},Nb,Pb=[null,[],[]],Qb=a=>0===a%4&&(0!==a%100||0===a%400),Rb=[31,29,31,30,31,30,31,31,30,31,30,31],Sb=[31,28,31,30,31,30,31,31,30,31,30,31];function Tb(a){var b=Array(qb(a)+1);pb(a,b,0,b.length);return b}
var Ub=(a,b,c,d)=>{function e(f,q,t){for(f="number"==typeof f?f.toString():f||"";f.length<q;)f=t[0]+f;return f}function g(f,q){return e(f,q,"0")}function m(f,q){function t(M){return 0>M?-1:0<M?1:0}var x;0===(x=t(f.getFullYear()-q.getFullYear()))&&0===(x=t(f.getMonth()-q.getMonth()))&&(x=t(f.getDate()-q.getDate()));return x}function h(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function l(f){var q=f.la;for(f=new Date((new Date(f.ma+1900,0,1)).getTime());0<q;){var t=f.getMonth(),x=(Qb(f.getFullYear())?Rb:Sb)[t];if(q>x-f.getDate())q-=x-f.getDate()+1,f.setDate(1),11>t?f.setMonth(t+1):(f.setMonth(0),f.setFullYear(f.getFullYear()+1));else{f.setDate(f.getDate()+q);break}}t=new Date(f.getFullYear()+1,0,4);q=h(new Date(f.getFullYear(),
0,4));t=h(t);return 0>=m(q,f)?0>=m(t,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var n=E[d+40>>2];d={ab:D[d>>2],$a:D[d+4>>2],ua:D[d+8>>2],ya:D[d+12>>2],va:D[d+16>>2],ma:D[d+20>>2],ia:D[d+24>>2],la:D[d+28>>2],eb:D[d+32>>2],Za:D[d+36>>2],bb:n?n?sb(A,n):"":""};c=c?sb(A,c):"";n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in n)c=c.replace(new RegExp(p,"g"),n[p]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),w="January February March April May June July August September October November December".split(" ");n={"%a":f=>u[f.ia].substring(0,3),"%A":f=>u[f.ia],"%b":f=>w[f.va].substring(0,3),"%B":f=>w[f.va],"%C":f=>g((f.ma+1900)/
100|0,2),"%d":f=>g(f.ya,2),"%e":f=>e(f.ya,2," "),"%g":f=>l(f).toString().substring(2),"%G":f=>l(f),"%H":f=>g(f.ua,2),"%I":f=>{f=f.ua;0==f?f=12:12<f&&(f-=12);return g(f,2)},"%j":f=>{for(var q=0,t=0;t<=f.va-1;q+=(Qb(f.ma+1900)?Rb:Sb)[t++]);return g(f.ya+q,3)},"%m":f=>g(f.va+1,2),"%M":f=>g(f.$a,2),"%n":()=>"\n","%p":f=>0<=f.ua&&12>f.ua?"AM":"PM","%S":f=>g(f.ab,2),"%t":()=>"\t","%u":f=>f.ia||7,"%U":f=>g(Math.floor((f.la+7-f.ia)/7),2),"%V":f=>{var q=Math.floor((f.la+7-(f.ia+6)%7)/7);2>=(f.ia+371-f.la-
2)%7&&q++;if(q)53==q&&(t=(f.ia+371-f.la)%7,4==t||3==t&&Qb(f.ma)||(q=1));else{q=52;var t=(f.ia+7-f.la-1)%7;(4==t||5==t&&Qb(f.ma%400-1))&&q++}return g(q,2)},"%w":f=>f.ia,"%W":f=>g(Math.floor((f.la+7-(f.ia+6)%7)/7),2),"%y":f=>(f.ma+1900).toString().substring(2),"%Y":f=>f.ma+1900,"%z":f=>{f=f.Za;var q=0<=f;f=Math.abs(f)/60;return(q?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":f=>f.bb,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(p in n)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),n[p](d)));
c=c.replace(/\0\0/g,"%");p=Tb(c);if(p.length>b)return 0;z.set(p,a);return p.length-1};K=k.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var Vb=Array(256),Wb=0;256>Wb;++Wb)Vb[Wb]=String.fromCharCode(Wb);Fa=Vb;P=k.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
S.prototype.isAliasOf=function(a){if(!(this instanceof S&&a instanceof S))return!1;var b=this.Z.ba.$,c=this.Z.aa,d=a.Z.ba.$;for(a=a.Z.aa;b.da;)c=b.qa(c),b=b.da;for(;d.da;)a=d.qa(a),d=d.da;return b===d&&c===a};S.prototype.clone=function(){this.Z.aa||Ia(this);if(this.Z.pa)return this.Z.count.value+=1,this;var a=Qa,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Z;a=a(c.call(b,d,{Z:{value:{count:e.count,na:e.na,pa:e.pa,aa:e.aa,ba:e.ba,ca:e.ca,fa:e.fa}}}));a.Z.count.value+=1;a.Z.na=!1;return a};
S.prototype["delete"]=function(){this.Z.aa||Ia(this);if(this.Z.na&&!this.Z.pa)throw new P("Object already scheduled for deletion");Ka(this);var a=this.Z;--a.count.value;0===a.count.value&&(a.ca?a.fa.ga(a.ca):a.ba.$.ga(a.aa));this.Z.pa||(this.Z.ca=void 0,this.Z.aa=void 0)};S.prototype.isDeleted=function(){return!this.Z.aa};
S.prototype.deleteLater=function(){this.Z.aa||Ia(this);if(this.Z.na&&!this.Z.pa)throw new P("Object already scheduled for deletion");Q.push(this);1===Q.length&&R&&R(Na);this.Z.na=!0;return this};k.getInheritedInstanceCount=()=>Object.keys(Oa).length;k.getLiveInheritedInstances=()=>{var a=[],b;for(b in Oa)Oa.hasOwnProperty(b)&&a.push(Oa[b]);return a};k.flushPendingDeletes=Na;k.setDelayFunction=a=>{R=a;Q.length&&R&&R(Na)};U.prototype.Ma=function(a){this.Ea&&(a=this.Ea(a));return a};
U.prototype.Ba=function(a){this.ga&&this.ga(a)};U.prototype.argPackAdvance=8;U.prototype.readValueFromPointer=bb;U.prototype.deleteObject=a=>{if(null!==a)a["delete"]()};
U.prototype.fromWireType=function(a){function b(){return this.ta?Ra(this.$.oa,{ba:this.Sa,aa:c,fa:this,ca:a}):Ra(this.$.oa,{ba:this,aa:a})}var c=this.Ma(a);if(!c)return this.Ba(a),null;var d=Pa(this.$,c);if(void 0!==d){if(0===d.Z.count.value)return d.Z.aa=c,d.Z.ca=a,d.clone();d=d.clone();this.Ba(a);return d}d=this.$.La(c);d=Ma[d];if(!d)return b.call(this);d=this.sa?d.Ia:d.pointerType;var e=La(c,this.$,d.$);return null===e?b.call(this):this.ta?Ra(d.$.oa,{ba:d,aa:e,fa:this,ca:a}):Ra(d.$.oa,{ba:d,aa:e})};
eb=k.UnboundTypeError=((a,b)=>{var c=Ta(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
Object.assign(lb.prototype,{get(a){return this.ja[a]},has(a){return void 0!==this.ja[a]},Ga(a){var b=this.Da.pop()||this.ja.length;this.ja[b]=a;return b},Ha(a){this.ja[a]=void 0;this.Da.push(a)}});X.ja.push({value:void 0},{value:null},{value:!0},{value:!1});X.za=X.ja.length;k.count_emval_handles=()=>{for(var a=0,b=X.za;b<X.ja.length;++b)void 0!==X.ja[b]&&++a;return a};
var Yb={l:a=>{var b=Ba[a];delete Ba[a];var c=b.xa,d=b.ga,e=b.Ca,g=e.map(m=>m.Pa).concat(e.map(m=>m.Wa));N([a],g,m=>{var h={};e.forEach((l,n)=>{var p=m[n],u=l.Na,w=l.Oa,f=m[n+e.length],q=l.Va,t=l.Xa;h[l.Ka]={read:x=>p.fromWireType(u(w,x)),write:(x,M)=>{var B=[];q(t,x,f.toWireType(B,M));Ca(B)}}});return[{name:b.name,fromWireType:l=>{var n={},p;for(p in h)n[p]=h[p].read(l);d(l);return n},toWireType:(l,n)=>{for(var p in h)if(!(p in n))throw new TypeError(`Missing field: "${p}"`);var u=c();for(p in h)h[p].write(u,
n[p]);null!==l&&l.push(d,u);return u},argPackAdvance:8,readValueFromPointer:Da,ha:d}]})},w:()=>{},F:(a,b,c,d)=>{b=O(b);L(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,g){return g?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(A[e])},ha:null})},t:(a,b,c,d,e,g,m,h,l,n,p,u,w)=>{p=O(p);g=V(e,g);h&&(h=V(m,h));n&&(n=V(l,n));w=V(u,w);var f=Sa(p);Va(f,function(){hb(`Cannot construct ${p} due to unbound types`,[d])});N([a,b,c],d?[d]:[],function(q){q=q[0];
if(d){var t=q.$;var x=t.oa}else x=S.prototype;q=Ta(f,function(){if(Object.getPrototypeOf(this)!==M)throw new P("Use 'new' to construct "+p);if(void 0===B.ka)throw new P(p+" has no accessible constructor");var wb=B.ka[arguments.length];if(void 0===wb)throw new P(`Tried to invoke ctor of ${p} with invalid number of parameters (${arguments.length}) - expected (${Object.keys(B.ka).toString()}) parameters instead!`);return wb.apply(this,arguments)});var M=Object.create(x,{constructor:{value:q}});q.prototype=
M;var B=new Wa(p,q,M,w,t,g,h,n);B.da&&(void 0===B.da.Aa&&(B.da.Aa=[]),B.da.Aa.push(B));t=new U(p,B,!0,!1);x=new U(p+"*",B,!1,!1);var xb=new U(p+" const*",B,!1,!0);Ma[a]={pointerType:x,Ia:xb};cb(f,q);return[t,x,xb]})},r:(a,b,c,d,e,g)=>{var m=ib(b,c);e=V(d,e);N([],[a],function(h){h=h[0];var l=`constructor ${h.name}`;void 0===h.$.ka&&(h.$.ka=[]);if(void 0!==h.$.ka[b-1])throw new P(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
h.$.ka[b-1]=()=>{hb(`Cannot construct ${h.name} due to unbound types`,m)};N([],m,n=>{n.splice(1,0,null);h.$.ka[b-1]=kb(l,n,null,e,g);return[]});return[]})},c:(a,b,c,d,e,g,m,h,l)=>{var n=ib(c,d);b=O(b);g=V(e,g);N([],[a],function(p){function u(){hb(`Cannot call ${w} due to unbound types`,n)}p=p[0];var w=`${p.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&p.$.Ta.push(b);var f=p.$.oa,q=f[b];void 0===q||void 0===q.ea&&q.className!==p.name&&q.ra===c-2?(u.ra=c-2,u.className=p.name,f[b]=u):
(Ua(f,b,w),f[b].ea[c-2]=u);N([],n,function(t){t=kb(w,t,p,g,m,l);void 0===f[b].ea?(t.ra=c-2,f[b]=t):f[b].ea[c-2]=t;return[]});return[]})},E:(a,b)=>{b=O(b);L(a,{name:b,fromWireType:c=>{var d=Y(c);mb(c);return d},toWireType:(c,d)=>T(d),argPackAdvance:8,readValueFromPointer:Da,ha:null})},p:(a,b,c)=>{b=O(b);L(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:nb(b,c),ha:null})},f:(a,b,c,d,e,g,m)=>{var h=ib(b,c);a=O(a);e=V(d,e);Va(a,function(){hb(`Cannot call ${a} due to unbound types`,
h)},b-1);N([],h,function(l){cb(a,kb(a,[l[0],null].concat(l.slice(1)),null,e,g,m),b-1);return[]})},d:(a,b,c,d,e)=>{b=O(b);-1===e&&(e=4294967295);e=h=>h;if(0===d){var g=32-8*c;e=h=>h<<g>>>g}var m=b.includes("unsigned")?function(h,l){return l>>>0}:function(h,l){return l};L(a,{name:b,fromWireType:e,toWireType:m,argPackAdvance:8,readValueFromPointer:ob(b,c,0!==d),ha:null})},b:(a,b,c)=>{function d(g){return new e(z.buffer,E[g+4>>2],E[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,
Uint32Array,Float32Array,Float64Array][b];c=O(c);L(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Qa:!0})},q:(a,b)=>{b=O(b);var c="std::string"===b;L(a,{name:b,fromWireType:d=>{var e=E[d>>2],g=d+4;if(c)for(var m=g,h=0;h<=e;++h){var l=g+h;if(h==e||0==A[l]){m=m?sb(A,m,l-m):"";if(void 0===n)var n=m;else n+=String.fromCharCode(0),n+=m;m=l+1}}else{n=Array(e);for(h=0;h<e;++h)n[h]=String.fromCharCode(A[g+h]);n=n.join("")}W(d);return n},toWireType:(d,e)=>{e instanceof ArrayBuffer&&(e=
new Uint8Array(e));var g="string"==typeof e;if(!(g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new P("Cannot pass non-string to std::string");var m=c&&g?qb(e):e.length;var h=Xb(4+m+1),l=h+4;E[h>>2]=m;if(c&&g)pb(e,A,l,m+1);else if(g)for(g=0;g<m;++g){var n=e.charCodeAt(g);if(255<n)throw W(l),new P("String has UTF-16 code units that do not fit in 8 bits");A[l+g]=n}else for(g=0;g<m;++g)A[l+g]=e[g];null!==d&&d.push(W,h);return h},argPackAdvance:8,readValueFromPointer:bb,
ha:d=>W(d)})},j:(a,b,c)=>{c=O(c);if(2===b){var d=ub;var e=vb;var g=yb;var m=()=>ja;var h=1}else 4===b&&(d=zb,e=Ab,g=Bb,m=()=>E,h=2);L(a,{name:c,fromWireType:l=>{for(var n=E[l>>2],p=m(),u,w=l+4,f=0;f<=n;++f){var q=l+4+f*b;if(f==n||0==p[q>>h])w=d(w,q-w),void 0===u?u=w:(u+=String.fromCharCode(0),u+=w),w=q+b}W(l);return u},toWireType:(l,n)=>{if("string"!=typeof n)throw new P(`Cannot pass non-string to C++ string type ${c}`);var p=g(n),u=Xb(4+p+b);E[u>>2]=p>>h;e(n,u+4,p+b);null!==l&&l.push(W,u);return u},
argPackAdvance:8,readValueFromPointer:Da,ha:l=>W(l)})},m:(a,b,c,d,e,g)=>{Ba[a]={name:O(b),xa:V(c,d),ga:V(e,g),Ca:[]}},g:(a,b,c,d,e,g,m,h,l,n)=>{Ba[a].Ca.push({Ka:O(b),Pa:c,Na:V(d,e),Oa:g,Wa:m,Va:V(h,l),Xa:n})},G:(a,b)=>{b=O(b);L(a,{Ra:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},I:(a,b,c)=>{a=Y(a);b=Cb(b,"emval::as");var d=[],e=T(d);E[c>>2]=e;return b.toWireType(d,a)},K:(a,b,c,d,e)=>{a=Fb[a];b=Y(b);c=Eb(c);var g=[];E[d>>2]=T(g);return a(b,c,g,e)},s:(a,b,c,d)=>{a=Fb[a];b=Y(b);
c=Eb(c);a(b,c,null,d)},u:mb,L:a=>{if(0===a)return T(Gb());a=Eb(a);return T(Gb()[a])},k:(a,b)=>{var c=Ib(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(p){return p.name}).join("_")+"$";var e=Jb[b];if(void 0!==e)return e;e=["retType"];for(var g=[d],m="",h=0;h<a-1;++h)m+=(0!==h?", ":"")+"arg"+h,e.push("argType"+h),g.push(c[1+h]);var l="return function "+Sa("methodCaller_"+b)+"(handle, name, destructors, args) {\n",n=0;for(h=0;h<a-1;++h)l+="    var arg"+h+" = argType"+h+".readValueFromPointer(args"+
(n?"+"+n:"")+");\n",n+=c[h+1].argPackAdvance;l+="    var rv = handle[name]("+m+");\n";for(h=0;h<a-1;++h)c[h+1].deleteObject&&(l+="    argType"+h+".deleteObject(arg"+h+");\n");d.Ra||(l+="    return retType.toWireType(destructors, rv);\n");e.push(l+"};\n");a=jb(e).apply(null,g);e=Hb(a);return Jb[b]=e},h:a=>{a=Eb(a);return T(k[a])},i:(a,b)=>{a=Y(a);b=Y(b);return T(a[b])},a:a=>{4<a&&(X.get(a).Fa+=1)},H:(a,b,c,d)=>{a=Y(a);var e=Lb[b];e||(e=Kb(b),Lb[b]=e);return e(a,c,d)},e:a=>T(Eb(a)),J:a=>{var b=Y(a);
Ca(b);mb(a)},n:(a,b)=>{a=Cb(a,"_emval_take_value");a=a.readValueFromPointer(b);return T(a)},o:()=>{fa("")},D:()=>{fa("OOM")},y:(a,b)=>{var c=0;Ob().forEach((d,e)=>{var g=b+c;e=E[a+4*e>>2]=g;for(g=0;g<d.length;++g)z[e++>>0]=d.charCodeAt(g);z[e>>0]=0;c+=d.length+1});return 0},z:(a,b)=>{var c=Ob();E[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);E[b>>2]=d;return 0},A:()=>52,C:()=>52,v:function(){return 70},B:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var m=E[b>>2],h=E[b+4>>2];b+=8;for(var l=0;l<h;l++){var n=
A[m+l],p=Pb[a];0===n||10===n?((1===a?ea:v)(sb(p,0)),p.length=0):p.push(n)}e+=h}E[d>>2]=e;return 0},x:(a,b,c,d)=>Ub(a,b,c,d)},Z=function(){function a(c){Z=c=c.exports;ha=Z.M;var d=ha.buffer;k.HEAP8=z=new Int8Array(d);k.HEAP16=C=new Int16Array(d);k.HEAPU8=A=new Uint8Array(d);k.HEAPU16=ja=new Uint16Array(d);k.HEAP32=D=new Int32Array(d);k.HEAPU32=E=new Uint32Array(d);k.HEAPF32=ka=new Float32Array(d);k.HEAPF64=la=new Float64Array(d);ma=Z.R;oa.unshift(Z.N);F--;k.monitorRunDependencies&&k.monitorRunDependencies(F);
0==F&&(null!==sa&&(clearInterval(sa),sa=null),G&&(d=G,G=null,d()));return c}var b={a:Yb};F++;k.monitorRunDependencies&&k.monitorRunDependencies(F);if(k.instantiateWasm)try{return k.instantiateWasm(b,a)}catch(c){v(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}za(b,function(c){a(c.instance)}).catch(ba);return{}}(),Xb=a=>(Xb=Z.O)(a),fb=a=>(fb=Z.P)(a);k.__embind_initialize_bindings=()=>(k.__embind_initialize_bindings=Z.Q)();var W=a=>(W=Z.S)(a),ta=()=>(ta=Z.T)();
k.dynCall_viijii=(a,b,c,d,e,g,m)=>(k.dynCall_viijii=Z.U)(a,b,c,d,e,g,m);k.dynCall_jiji=(a,b,c,d,e)=>(k.dynCall_jiji=Z.V)(a,b,c,d,e);k.dynCall_iiiiij=(a,b,c,d,e,g,m)=>(k.dynCall_iiiiij=Z.W)(a,b,c,d,e,g,m);k.dynCall_iiiiijj=(a,b,c,d,e,g,m,h,l)=>(k.dynCall_iiiiijj=Z.X)(a,b,c,d,e,g,m,h,l);k.dynCall_iiiiiijj=(a,b,c,d,e,g,m,h,l,n)=>(k.dynCall_iiiiiijj=Z.Y)(a,b,c,d,e,g,m,h,l,n);var Zb;G=function $b(){Zb||ac();Zb||(G=$b)};
function ac(){function a(){if(!Zb&&(Zb=!0,k.calledRun=!0,!ia)){qa=!0;Aa(oa);aa(k);if(k.onRuntimeInitialized)k.onRuntimeInitialized();if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;){var b=k.postRun.shift();pa.unshift(b)}Aa(pa)}}if(!(0<F)){if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)ra();Aa(na);0<F||(k.setStatus?(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},1);a()},1)):a())}}
if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();ac();


  return moduleArg.ready
}

);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = MeshUtility;
else if (typeof define === 'function' && define['amd'])
  define([], () => MeshUtility);
